/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;
import civitas.CivitasJuego;
import civitas.Diario;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vistaTextualCivitas.Vista;

/**
 *
 * @author Fernando
 */
public class CivitasView extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form CivitasView
     */
    
    private CivitasJuego juego;

    public void setCivitasJuego (CivitasJuego j) {
        juego = j;
        setVisible(true);
        label_ranking.setVisible(false);
        text_ranking.setVisible(false);
    }
    
    
    @Override
    public void actualiza (){
        
        jugadorPanel1.setJugador(juego.getJugadorActual());
        casillaActualPanel1.setCasilla(juego.getTablero().getCasilla(juego.getJugadorActual().getCasillaActual()));
        
        if (juego.finalDelJuego()){
            label_ranking.setVisible(true);
            text_ranking.setVisible(true);
            
            juego.ranking();
            
            String rank = "";

            for (int i=0; i < juego.getJugadores().size(); i++){
                
                rank += "Puesto número " + String.valueOf(i+1) + ": \n" + juego.getJugadores().get(i).toString() + "\n";
                
            }
            
            text_ranking.setText(rank);
            
            repaint();
            revalidate();
        }
        
    }
    
    public CivitasView() {
        initComponents();
    }
    
    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
        "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
    }
       
    public Respuesta comprar(){
        int val= JOptionPane.showConfirmDialog(null, "¿Comprar la calle actual?",
        "Compra", JOptionPane.YES_NO_OPTION);
        if (val==0){
            return Respuesta.SI;
        }else{
            return Respuesta.NO;
        }
    }

    public OperacionInmobiliaria elegirOperacion(){
        
        GestionarDialog gestion;
       
        gestion = new GestionarDialog(this);
        
        switch (gestion.getGestion()) {
            case 0:
                return OperacionInmobiliaria.CONSTRUIR_CASA;
            case 1:
                return OperacionInmobiliaria.CONSTRUIR_HOTEL;
            default:
                return OperacionInmobiliaria.TERMINAR;
        }   
        
    }

    public int elegirPropiedad(){
           
        PropiedadDialog propiedad;
       
        propiedad = new PropiedadDialog(this, juego.getJugadorActual());
        
        return propiedad.getPropiedadElegida();
        
    }

    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        
        text_operacion.setText(operacion.toString());
        
        if (operacion == OperacionJuego.AVANZAR){
            Dado.createInstance(this);
        }
                
        System.out.println(operacion.toString());
        
        
        repaint();
        revalidate();
        
    }
    
    public void mostrarEventos() {
        
        DiarioDialog diarioD;
        
        if (!Diario.getInstance().getEventos().isEmpty())
            diarioD = new DiarioDialog(this); //crea la ventana del diario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        casillaActualPanel1 = new GUI.CasillaActualPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_operacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_ranking = new javax.swing.JTextArea();
        label_ranking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("CIVITAS");
        jLabel1.setName("titulo_civitas"); // NOI18N

        jLabel2.setText("JUGADOR ACTUAL:");

        jLabel3.setText("CASILLA ACTUAL:");

        jLabel4.setText("SIGUIENTE OPERACION:");

        text_operacion.setEditable(false);
        text_operacion.setText("operacion");

        text_ranking.setEditable(false);
        text_ranking.setColumns(20);
        text_ranking.setRows(5);
        text_ranking.setBorder(null);
        jScrollPane1.setViewportView(text_ranking);

        label_ranking.setText("RANKING:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casillaActualPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(text_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ranking)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(casillaActualPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(label_ranking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLabel1.getAccessibleContext().setAccessibleName("titulo_civitas");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaActualPanel casillaActualPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JLabel label_ranking;
    private javax.swing.JTextField text_operacion;
    private javax.swing.JTextArea text_ranking;
    // End of variables declaration//GEN-END:variables
}
